<div class="container">
    <div class="row">
		<?php 
			echo $this->flashMessenger()->render();
		?>
		<div class="panel panel-default">
		  	<!-- Default panel contents -->
		  	<div class="panel-heading">
		  		<span class="pull-left"><h4>Danh sách các Form đã tạo</h4></span>
		  		<div class="pull-right">
			  		<span ><button class="btn btn-info" id="addNew" type="button">Add New Form</button></span>
			  		<span ><a class="btn btn-warning" href="<?php echo $this->url('home/default',array('action' => 'logout')) ?>">Logout</a></span>
		  		</div>
		  		<div class="clearfix"></div>
		  	</div>
		  	<!-- Table -->
		  	<table class="table">
		    	<thead>
		    		<tr>
		    			<th><input type="checkbox" id="selectall" name="inputCheck[]" ></th>
		    			<th>Tên Form</th>
		    			<th>Created date</th>
		    			<th>Created by</th>
		    			<th>Status</th>
		    			<th>ID</th>
		    			<th>Action</th>
		    			<th>Remove</th>
		    		</tr>
		    	</thead>
		    	<tbody>
		    		<?php 
		    			$list = '';
		    			if(count($listForm) > 0){
		    				foreach ($listForm as $key => $form) {
		    				$list .= '<tr>';
		    					$status = 'inactive';
		    					if($form['status'] == 'draf'){
		    						$status = '<span class="text-info">draf</span>';
		    					}else if($form['status'] == 'active'){
		    						$status = '<span class="text-success">active</span>';
		    					}  
		    					$list .= sprintf(
		    							'<td><input type="checkbox" class="second" name="inputCheck[]" ></td>
		    							 <td><a href="%s">%s</a></td>
		    							 <td>%s</td>
		    							 <td>%s</td>
		    							 <td>%s</td>
		    							 <td>%s</td>
		    							 <td>%s</td>,
		    							 <td >%s</td>',
		    							 $this->url('form/default',array("action" => 'editForm','id' => $form['id'])),
		    							 $form['name'],date('d-m-Y', $form['created_date']), $form['username'],
		    							 $status,
		    							 $form['id'],
		    							 '<a href="' . $this->url('code/default',['action' => 'createCode','id' => $form['id']]) . '">Create Code</a>',
		    							 '<a href="' . $this->url('form/default',['action' => 'remove','id' => $form['id']]) . '"><span class="delete-close"></span></a>');
		    				$list .= '</tr>';
		    				}
		    			}else{
		    			
		    				$list .=  "<tr><td>Chưa có Form được tạo<td></tr>";
		    			}

		    			echo $list;
		    		?>
		    	</tbody>
		  	</table>
		</div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function() {	
		$("#addNew").click(function(){
			window.location.href = "<?php echo $this->url("code") ?>" ;
		})
		
		$(".second").click(function() {
			$("#selectall").prop("checked", false);
		});
		
		$("#selectall").click(function() {
			$(".second").prop("checked", $("#selectall").prop("checked"))
		})


});
</script>
