<?php foreach($this->infoForm->content as $nameElement => $infoElement): ?>
	<?php if($nameElement == 'renameInfo'): continue; ?>
	<?php else: ?>
	<div class="row box hide elementAttrs" >
		<div class="wrapper-<?php echo $nameElement ?>">
			<div class="col-md-12">
				<span class="hide span-name-element-hidden pull-left"></span>
				<span class="glyphicon glyphicon-remove pull-right removeElement" onclick="removeElement(this)"></span>
				<span class="glyphicon glyphicon-minus pull-right openElement"></span>
			</div>
			<div class="wrap">
				<div class="col-md-6">
					<h3 class="name-element">[...] Element</h3>
					<span onclick="changeNameElement(this)" title="change name element" class="glyphicon glyphicon-pencil"></span>
					<input type="hidden" class="rename" name="renameInfo[<?php echo @$nameElement?>]"></input>
					<input type="hidden" name="name" value="<?php echo @$infoElement->name ?>" class="input-name-element-hidden">
					<div class="row" style="margin-bottom: 30px;">
						<div class="col-md-12 tab tabAttribute">
							<h4>Attributes &amp; Options</h4>
						</div>
						<!-- <div class="col-md-6 tab tabOption">
								<h4>Options</h4>
							</div> -->
					</div>

					<div class="row attribute">
						<!-- CONVERT AREA -->
						<div class="convertArea">
							<div class="col-md-10">
								<div class="form-group">					
									<label >Convert</label>
									<textarea class="form-control" rows="5" name="convertInput"></textarea>
								</div>
							</div>
							
							<div class="col-md-2">
								<div class="form-group ">
									<label>&nbsp;</label><br/><br/>
									<button class="btn btn-primary" onclick="convertElement(this,'.wrapper-<?php echo $nameElement ?>');" type="button">Convert</button>
								</div>
							</div>
						</div>

						<!-- OPTIONS -->
						<div class="col-md-4">
							<div class="form-group">					
								<label for="id">Label name</label>
								<input type="text" value="<?php echo @$infoElement['option']['nameLabel'] ?>"  name="nameLabel" class="form-control nameLabel"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="class">Label class</label>
								<input type="text" value="<?php echo @$infoElement['option']['classLabel'] ?>" name="classLabel" class="form-control classLabel"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="placeElement">For</label><br/>
								<input type="text" value="<?php echo @$infoElement['option']['forLabel'] ?>" id="forLabel" class="form-control forLabel"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="disableHtml">Html escape label</label><br/>
								<?php $checked =  @$infoElement['option']['disableHtml'] == 'on'? 'checked="checked"' : '' ?>
								<input type="checkbox" class="form-control disableHtml" <?php echo $checked ?> name="requiredElement"/>
							</div>
						</div>

						<div class="selectbox hide">
							<div class="col-md-4">
								<div class="form-group">
									<label for="emptyOption">Empty option</label><br/>
									<input type="text" value="<?php echo @$infoElement['option']['emptyOption'] ?>" name="emptyOption" class="form-control emptyOption"/>
								</div>
							</div>

							<div class="col-md-4">
								<div class="form-group">
									<label for="valueOption">Value option</label><br/>
									<input type="text" name="valueOption" value="<?php echo @$infoElement['option']['valueOption'] ?>" placeholder="1,2,3,4" class="form-control valueOption"/>
								</div>
							</div>

							<div class="col-md-4">
								<div class="form-group">
									<label for="nameOption">Name option</label><br/>
									<input type="text" name="nameOption" value="<?php echo @$infoElement['option']['nameOption'] ?>" placeholder="name1,nam2,name3,name4" class="form-control nameOption"/>
								</div>
							</div>
						</div>
						<!-- END OPTIONS -->

						<!-- ATTRIBUTES -->
						<div class="col-md-4">
							<div class="form-group">					
								<label for="type">Type</label>
								<select class="form-control typeElement" name="typeElement">
									<option value="text">Text</option>
									<option value="button">Button</option>
									<option value="select">Select</option>
									<option value="checkbox">Checkbox</option>
									<option value="textarea">Textarea</option>
									<option value="color">Color</option>
									<option value="date">Date</option>
									<option value="datetime">Datetime</option>
									<option value="dateime-local">Datetime-local</option>
									<option value="email">Email</option>
									<option value="file">File</option>
									<option value="hidden">Hidden</option>
									<option value="image">Image</option>
									<option value="month">Month</option>
									<option value="number">Number</option>
									<option value="password">Pasword</option>
									<option value="radio">Radio</option>
									<option value="range">Range</option>
									<option value="reset">Reset</option>
									<option value="search">Search</option>
									<option value="submit">Submit</option>
									<option value="tel">Tel</option>
									<option value="time">Time</option>
									<option value="url">Url</option>
									<option value="week">Week</option>
								</select>
							</div>
						</div>
						<div class="col-md-4">
							<div class="form-group">					
								<label for="id">ID</label>
								<input type="text" value="<?php echo @$infoElement['attribute']['id'] ?>"  name="idElement" class="form-control idElement"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="class">Class</label>
								<input type="text" value="<?php echo @$infoElement['attribute']['class'] ?>" name="classElement" class="form-control classElement"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="placeElement">Placeholder</label><br/>
								<input type="text" value="<?php echo @$infoElement['attribute']['placeholder'] ?>" name="placeElement" class="form-control placeElement"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="valueElement">Value</label><br/>
								<input type="text" name="valueElement" value="<?php echo @$infoElement['attribute']['value'] ?>" class="form-control valueElement"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="requiredElement">Required</label><br/>
								<?php $checked =  @$infoElement['required'] == 'on'? 'checked="checked"' : '' ?>
								<input type="checkbox" class="form-control requiredElement" <?php echo $checked ?> name="requiredElement"/>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="attrElement">Attributes</label><br/>
								<textarea class="form-control attrElement" name="attrElement" placeholder="attr1 : name1,attr2 : name2" ><?php echo @$infoElement['attribute']['attr'] ?></textarea>
							</div>
						</div>

						<div class="col-md-4">
							<div class="form-group">
								<label for="placeElement">Option label</label><br/>
								<textarea placeholder="op1:name1,op2:name2" class="form-control optionLabel"><?php echo @$infoElement['option']['optionLabel'] ?></textarea>
							</div>
						</div>
						<!-- END ATTRIBUTES -->			 
					</div>

					
					<hr />

					<div class="row">
						<div style="margin-bottom: 30px;">
							<div class="col-md-6 tab tabValidate">
								<h4>Validate</h4>
							</div>
							<div class="col-md-6 tab tabFilter">
								<h4>Filter</h4>
							</div>
						</div>
					</div>
					<!-- VALIDATE AREA -->
					<div class="row validateArea" >
						<div class="col-md-10">
							<div class="form-group" >
								<label>&nbsp;</label><br/>
								<select name="validateElement" class="form-control">
									<?php					    			
									$list = "<option value='not-validate'>Choose Validate Type</option>";
									foreach($this->validateElement as $vali){
										$list .= '<option value="'. ($vali['name']) .'">'. $vali['name'] .'</option>';
									}
									echo $list;
									?>
								</select>
							</div>
							<ul class="validateList"> </ul>    
						</div>				 
						<div class="col-md-2">
							<div class="form-group ">
								<label>&nbsp;</label><br/>
								<button class="btn btn-primary setValidate" type="button">Set validate</button>
							</div>
						</div> 					 
					</div>
					<!-- END VALIDATE AREA -->

					<!-- FILTER AREA -->
					<div class="row hide filterArea" >
						<div class="col-md-10">
							<div class="form-group" >
								<label>&nbsp;</label><br/>
								<select name="filterElement" class="form-control">
									<?php				    			
									$list = "<option value='not-filter'>Choose Filter Type</option>";
									foreach($this->filterElement as $vali){
										$list .= '<option value="'. ($vali['name']) .'">'. $vali['name'] .'</option>';
									}
									echo $list;
									?>				    	
								</select>
							</div>
							<ul class="filterList"> </ul>    
						</div>					 
						<div class="col-md-2">
							<div class="form-group ">
								<label>&nbsp;</label><br/>
								<button class="btn btn-primary setFilter" type="button">Set filter</button>
							</div>
						</div> 					 
					</div>
					<!-- END FILTER -->

				</div>

				<div class="pull-right col-md-6 display-code">
					<h3>Code</h3>
					<div class="row-show-code hide" style="margin-bottom: 70px;">
						<div class="col-md-6 tab elementForm">
							<h4>Element Form</h4>
						</div>
						<div class="col-md-6 tab filterValidate">
							<h4>Filter &amp; Validate</h4>
						</div>
					</div>
					
					<div  name="code" class="form-control code">

					</div>
				</div>

				<div class="col-md-6 col-md-offset-3 text-center" style="margin-top:80px;margin-bottom:20px">
					<button type="button" class="btn btn-primary previewElement" >Preview Code</button>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
<?php endforeach; ?>
