<div class="row">

    <?php 
      $form->prepare();
      echo $this->flashMessenger()->render();
      echo $form->showError();
      echo @$errorAuth;
    ?>
    <div class="col-md-4 col-md-offset-4">
    <?php 
          if($flag == 'login'){
              echo $this->form()->openTag($form);
                  echo $this->formElement($form->get('inputCsrf'));
                  echo $this->formLabel($form->get('inputEmail')) .$this->formElement($form->get('inputEmail'));
                  echo $this->formLabel($form->get('inputPassword')) . $this->formElement($form->get('inputPassword'));
                  echo $this->formButton($form->get('dangnhap'));
                  echo $this->formButton($form->get('dangky'));
                  echo $this->formButton($form->get('back'));
              echo $this->form()->closeTag();
          }else{
              echo $this->form()->openTag($form);
                  echo $this->formElement($form->get('inputCsrf'));
                  echo $this->formLabel($form->get('inputName')) . $this->formElement($form->get('inputName'));
                  echo $this->formLabel($form->get('inputEmail')) . $this->formElement($form->get('inputEmail'));
                  echo $this->formLabel($form->get('inputPassword')) . $this->formElement($form->get('inputPassword'));
                  echo $this->formLabel($form->get('inputRepassword')) . $this->formElement($form->get('inputRepassword'));
                  echo $this->formButton($form->get('dangky'));
                  echo $this->formButton($form->get('back'));
              echo $this->form()->closeTag();
          }
    ?>  
    </div>
</div>
<script>
    $(document).ready(function(){
        var flag = '<?php echo $flag ?>';
        var action = "<?php echo $this->url("home/default",["action" => "signup"]) ?>";

        $("#dangnhap").on('click',function(){
            $("form[name=loginForm]").submit();
        })

        if(flag === 'signup'){
              if($("#back").hasClass('hide')){
                  $("#back").removeClass('hide ').addClass('animated rotateIn');
              }

              $("#dangky").css("margin-top","20px");
              $("#dangky").on('click',function(e){
                  $("form[name=loginForm]").attr("action",action).submit();
              })

        }

        $("#back").click(function(){
            $("#back").addClass("animated rotateOut");

            setTimeout(function(){
                if(flag === "login"){
                  location.reload()
                }else{
                  window.location.href = "<?php echo BASE_URL .  $this->url('home') ?>"
                }
            },700);

        })

        var isClicked = false;
        $("#dangky").on('click',function(e){
            if(isClicked === false){
                $("#dangky").css("margin-top","20px");
                $("#dangnhap").remove();
                $("#back").removeClass("hide").addClass("animated rotateIn");
                $("form[name=loginForm]").prepend('<?php echo $this->formLabel($form->get('inputName')) . $this->formElement($form->get('inputName')) ?>');
                $('<?php echo $this->formLabel($form->get('inputRepassword')) . $this->formElement($form->get('inputRepassword')) ?>').insertAfter("#inputPassword");
                
                isClicked = true;
            }else{  
  
                $("form[name=loginForm]").attr("action",action).submit();

            }
        })


        
    })
</script>