<?php
	$listTableNames = $this->listTableNames();
 ?>
<section class="table-list">
	<div class="hide">
		<input type="hidden" name="urlGetField" value="<?php echo BASE_URL . $this->url('autoDb/default',[ 'action' => 'getListField']) ?>">
	</div>
	<div class="container">
		<div class="row col-md-3">
			<select class="list-table form-control">
				<option value="empty">---- List table ----</option>
				<?php
					if(!empty($listTableNames)){
						foreach($listTableNames as $table){
							echo "<option value='" . strtolower($table) ."'>" . $table . "</option>";
						}
					}
				?>
			</select>
		</div>
		<div class="col-md-2">
			<button type="button"  class="add-table btn btn-info form-control">Add</button>
		</div>
	</div>
</section>

<section class="field-list" style="display: none">
	<h3 class="display-name-table">[filters] Table</h3>
	<div id="table-wrapper">
		<table class="table">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="selectall" name="all">
					</th>
					<th>Field</th>
					<th>Type</th>
				</tr>
			</thead>
			<tbody class="display-field"></tbody>
		</table>
	</div>
	<div class="row">
		<div class="col-md-4">
			<button class="btn-display-select btn btn-info btn-sm" type="button">SELECT</button>
			<button class="btn-display-insert btn btn-info btn-sm" type="button">INSERT</button>
			<button class="btn-display-update btn btn-info btn-sm" type="button">UPDATE</button>
			<button class="btn-display-delete btn btn-info btn-sm" type="button">DELETE</button>
		</div>
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-3">
					<select class="conditional-name form-control">
						<option value="->equal(">Where =</option>
						<option value="->notEqual(">Where !=</option>
						<option value="->in(">Where In</option>
						<option value="->notIn(">Where Not in</option>
						<option value="->between(">Where Between</option>
						<option value="->notBetween(">Where Not between</option>
						<option value="->greaterThan(">Where ></option>
						<option value="->greaterThanOrEqualTo(">Where >=</option>
						<option value="->lessThan(">Where <</option>
						<option value="->lessThanOrEqual(">Where <=</option>
						<option value="->like(">Where Like</option>
						<option value="->notLike(">Where Not like</option>
						<option value="->literal(">Where Literal</option>
					</select>
				</div>
				<div class="col-md-5">
					<input id="autocomplete-field" placeholder="id,69" class="form-control conditional-value"></input>
				</div>
				<button class="btn-add-chain btn btn-info btn-sm" type="button">ADD CHAIN</button>
				<button class="btn-add-new btn btn-info btn-sm" type="button">ADD NEW</button>
			</div>
		</div>
	</div>
</section>


<section class="display-sql code2" id="auto-db">

</section>
<script type="text/javascript">
	;(function($, window, document, undefined){
	"use strict";

	$(document).ready(function(){
		new Clipboard('.btn');
		var nest               = '';
		var unnest             = '';
		(function(){
			var btnAddTable        = $('.add-table');
			var listTable          = $('.list-table');
			var btnDisplaySelect   = $('.btn-display-select');
			var btnDisplayInsert   = $('.btn-display-insert');
			var btnDisplayUpdate   = $('.btn-display-update');
			var btnDisplayDelete   = $('.btn-display-delete');
			var btnDisplayCustom   = $('.btn-display-custom');
			var btnAddChain        = $('.btn-add-chain');
			var sltConditionalName = $('.conditional-name');
			var stringWhere        = '';
			var flagWhere          = '';
			var space              = '';

			sltConditionalName.on('change',function(){// change Placeholder & Title  when select Conditional
				switch ($(this).val()) {
					case "whereliteral":
						$("#autocomplete-field").attr("placeholder","id = 69");
						$("#autocomplete-field").attr("title","id = 69");
						break;
					case "->in(":
					case "->notIn(":
						$("#autocomplete-field").attr("placeholder","id,6,7,8,9");
						$("#autocomplete-field").attr("title","id,6,7,8,9");
						break;
					case "->between(":
					case "->notBetween(":
						$("#autocomplete-field").attr("placeholder","id,6,9");
						$("#autocomplete-field").attr("title","id,6,9");
				break;
					case "->like(":
					case "->notLike(":
						$("#autocomplete-field").attr("placeholder","id,'%jav%'");
						$("#autocomplete-field").attr("title","id,'%jav%'");
				break;
					default:
					$("#autocomplete-field").attr("placeholder","id,69");
					$("#autocomplete-field").attr("title","id,69");
				}
			})//end


			btnAddTable.on('click',function(){//handle for ADD TABLE
				if(listTable.val() !== ''){
					getListField(listTable.val());//ajax to create template table list Field
				}
			})//end

			btnDisplaySelect.on('click',function(){//hande for SELECT
					var listNameChecked = getListNameChecked();
					var stringSql       = createStringSql(listNameChecked,"select");
					if(stringWhere !== '' && flagWhere !== ''){
						stringWhere = '';
						flagWhere   = '';
					}
					$(".display-sql").html(stringSql);
			})//end

			btnDisplayInsert.on('click',function(){//hande for INSERT
					var listNameChecked = getListNameChecked();
					var stringSql       = createStringSql(listNameChecked,"insert");

					$(".display-sql").html(stringSql);
			})//end

			btnDisplayUpdate.on('click',function(){//hande for UPDATE
					var listNameChecked = getListNameChecked();
					var stringSql       = createStringSql(listNameChecked,"update");
					if(stringWhere !== ''){
						stringWhere = '';
					}
					$(".display-sql").html(stringSql);
			})//end

			btnDisplayDelete.on('click',function(){//hande for DELETE
					var listNameChecked = getListNameChecked();
					var stringSql       = createStringSql(listNameChecked,"delete");
					if(stringWhere !== ''){
						stringWhere = '';
					}
					$(".display-sql").html(stringSql);
			})//end

			btnAddChain.on('click',function(){//handle for ADD CHAIN
				var conName     = $(".conditional-name").val();
				var conValue    = $(".conditional-value").val();
				if(conName !== '' && conValue !== ''){
					if(flagWhere === ''){// first time assign '->where'
						var charWhere = '->where';
						space         = 17;
						flagWhere     = 'notNull';
					}else{// not first time will not '->where'
						var charWhere = '';
						space         = 24;
					}//end

					stringWhere += handleWhereStatement(conName,conValue,charWhere,space);

					$(".conditional-area").html(stringWhere);
				}
			})//end

		})();

		var createStringSql = function(listName = '',type = 'select'){
			listName = (listName.length === 0)? '' :  mK("array") + mP("(") + listName.join(",") + mP(")");
			var html = '';

			switch(type){
				case "insert":
					html = mK("public function") + mP(" addItem(") + mV("$data") + mP(" = ") + "null" + mP(",") + mV("$options") + mP(" = ") + "null" + mP("\)\{") + "<br/>";
						html += rPt() + mV("$this") + mP("->_tableGateway->insert(") + mV("$data") + mP(")") + mP(";") + "<br/>";
						html += rPt() + mK("return ") + mV("$result") + mP(";") + "<br/>";
					html += mP("}") + "<br/>";
					break;
				case "update":
					html = mK("public function") + mP(" updateItem(") + mV("$data") + mP(" = ") + "null" + mP(",") + mV("$options") + mP(" = ") + "null" + mP("\)\{") + "<br/>";
						html += rPt() + mV("$this") + mP("->_tableGateway->update(") + mV("$data") + mP(")") + mP(";") + "<br/>";
						html += rPt() + mK("return ") + mV("$result") + mP(";") + "<br/>";
					html += mP("}") + "<br/>";
					break;
				case "delete":
					html = mK("public function") + mP(" deleteItem(") + mV("$data") + mP(" = ") + "null" + mP(",") + mV("$options") + mP(" = ") + "null" + mP("\)\{") + "<br/>";
						html += rPt() + mV("$this") + mP("->_tableGateway->delete(") + mV("$data") + mP(")") + mP(";") + "<br/>";
						html += rPt() + mK("return ") + mV("$result") + mP(";") + "<br/>";
					html += mP("}") + "<br/>";
					break;
				default :
					html = mK("public function") + mP(" listItem(") + mV("$data") + mP(" = ") + "null" + mP(",") + mV("$options") + mP(" = ") + "null" + mP("\)\{") + "<br/>";
						html += rPt() + mV("$result") + mP(" = ") + mV("$this") + mP("->_tableGateway->select(") + mK("function") + mP("(") + mK("Select ") + mV("$select") + mP(")") + mK("use") + mP("(") + mV("$data") + mP(")") + mP("{") + "<br/>";
							html += rPt(10) + mV("$select") + mP("->columns(") + listName + mP(")") + "<span class='conditional-area'></span>" + mP(";") + "<br/>";
						html += rPt() + mP("})->toArray();") + "<br/>";
						html += rPt() + mK("return ") + mV("$result") + mP(";") + "<br/>";
					html += mP("}") + "<br/>";
			}

			return '<div class="code-area"><code><button class="btn pull-right copy-all" type="button" data-clipboard-target="#auto-db">'
				+ '<img src="https://zenorocha.github.io/clipboard.js/assets/images/clippy.svg" width="13" height="15"></button>'
				+ html + '</code></div>';
		}//end createStringSql

		var notEasyAutoComplete = function(listTable){
			$( "#autocomplete-field" ).autocomplete({
				source: listTable
			});
		}//end notEasyAutoComplete

		var resetWhere = function(stringWhere,charWhere){
			if(stringWhere !== '' && charWhere !== ''){
				stringWhere = '';
				charWhere   = '';
			}
		}//end resetWhere

		var getListNameChecked = function(){
			var tmpListNameChecked = [];
			$('input[name|="check"]').each(function(val){
					if($(this).is(":checked")){
						var name = $(this).attr('name');
						name     = name.replace("check-","");
						tmpListNameChecked.push("'" + name + "'");
					}
			})
			return tmpListNameChecked;
		}//end getListNameChecked

		var getListField = function(nameTable = ''){
			$.ajax({
				url      : $("[name =urlGetField]").val(),
				type     : "POST",
				dataType : 'json',
				data : {
					action    : "view",
					nameTable : nameTable
				},
				success : function(data){
					if(data.listFieldNames !== ''){
						var listField = data.listFieldNames;
						var html = '';

						$(".field-list").show();

						$(".display-name-table").html('<h3>[' + nameTable + '] Table</h3>')

						for (var key in listField) {
							if (listField.hasOwnProperty(key)) {
								html += '<tr>' +
													'<th scope="row"><input type="checkbox"  class="second" name="check-'+ key +'"></th>' +
													'<td>'+ key +'</td>' +
													'<td>'+ listField[key] +'</td>' +
												'</tr>' ;
							}
						}

						$(".display-field").html(html);
						notEasyAutoComplete(data.listFieldLiteral);

						/** FUCTION */
						checkAll();
					}
				}
			})
		}//end getListField

		var checkAll = function(){
			$(".second").on('click',function() {
					$("#selectall").prop("checked", false);
			});

			$("#selectall").on('click',function() {
					$(".second").prop("checked", $("#selectall").prop("checked"));
			})
		}// end checkAll

		/*************************************
		 * Handle Statement
		 *************************************/

		var handleWhereStatement = function (conName = '',conValue = '',charWhere = '',space = ''){
			var stringWhere = '';

			if(conValue.search(/,or/) != -1){//if found 'or'
				// if(nest === '' && unnest === ''){//first time set 'nest' and 'unnest'
					conValue = conValue.replace(/,or/,"");

					nest      = mP("->NEST") + "<br/>" + rPt(space + 7);
					unnest    = "<br/>" + rPt(space) + mP("->UNNEST");

					charWhere = charWhere + nest;
			}else{//else if not found 'or'
					nest   = '';
					unnest = '';
			}//end

			if(conValue.search(/,with/) != -1){//if found 'with'
				// if(nest === '' && unnest === ''){//first time set 'nest' and 'unnest'
					conValue = conValue.replace(/,with/,"");

					nest      = mP("->NEST") + "<br/>" + rPt(space + 7);
					unnest    = "<br/>" + rPt(space) + mP("->UNNEST");

					charWhere = charWhere + nest;
			}//end

			if(conValue.search(/,/) != -1){ //if found ',' ---> for WHERE * ,but LITERAL
				if(conName === "wherein" || conName === "wherenotin"){ //check to handle conditionalValue
					conValue  = convertToQuotes(conValue,"in");
				}else{
					conValue  = convertToQuotes(conValue);
				}//end
			}else{// for WHERE LITERAL
				conValue = "'" + conValue + "'";
			}//end

			return stringWhere = "<br/>" + rPt(space) + mP(charWhere + conName) + conValue + mP(")") + unnest;

		}

		/*************************************
		 * Utilities
		 *************************************/
		function mK(text = ''){
			if(text !== ''){
				return "<span class='php-keyword'>" + text +"</span>";
			}
		}

		function mV(text = ''){
			if(text !== ''){
				return "<span class='php-variable'>" + text +"</span>";
			}
		}

		function mP(text = ''){
			if(text !== ''){
				return "<span class='php-plain'>" + text +"</span>";
			}
		}

		function mC(text = ''){
			if(text !== ''){
				return "<span class='php-comment'>" + text +"</span>";
			}
		}

		function rPt(step = 5){
			return "&nbsp;".repeat(step);
		}

		var convertToQuotes = function(string,style = 'normal'){
			var newString = [];

			string        = string.split(",");
			newString.push('"' + string[0] + '"');//

			string.shift()
			if(style === 'in'){// handle for IN and NOT IN predicate
				string = string.join(",");
				newString.push(mP("array(") + string + mP(")"));
			}//end

			if(style === 'normal'){ //handle for others predicate
				newString.push(string);
			}//end

			return newString.join(",");
		}
		/**************************************/

	});

})(jQuery, window, document);

</script>
