<section class="wrapper site-min-height">
    <div class="row">
        <?php echo $this->flashMessenger()->render() ?>
        <div class="col-lg-12">
            <section class="panel panel-primary">         
                <div class="panel-body">
                    <div class="pull-right">
                        <h4><a href="<?php echo  $this->url('demo_user/default',['action' => 'add']) ?>">ADD USER</a></h4>
                    </div>
                    <section id="flip-scroll">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th>Họ Và Tên</th>
                                    <th>Email</th>
                                    <th>Địa chỉ</th>
                                    <th style="text-align:center;">Số ĐT</th>
                                    <th style="text-align:center;">Nhóm</th>
                                    <th style="text-align:center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($this->items): ?>
                                    <?php foreach ($this->items as $item): ?>
                                        <tr>
                                            <td>
                                                <a class="tooltips" data-placement="top" data-original-title="Xem thông tin người dùng" href="<?php echo $this->url("demo_user/default",['action' => 'add' ,'id' => $item['user_id']] ) ?>">
                                                    <?php echo $item['fullname']; ?>
                                                </a>
                                            </td>
                                            <td><?php echo $item['email']; ?> </td>
                                            <td><?php echo $item['address']; ?> </td>
                                            <td style="text-align:center;"><?php echo $item['phone']; ?></td>
                                            <td style="text-align:center;">
                                                <?php echo $item['group_name'] ?>
                                            </td>
                                            <td style="text-align:center;">
                                                <a href="<?php echo  $this->url('demo_user/default',['action' => 'destroy','id' => $item['user_id']]) ?>" class="glyphicon glyphicon-floppy-remove" data-placement="top" data-original-title="Xóa người dùng"></a>     
                                            </td>                                           
                                        </tr>

                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="6" style="text-align:center;">Hiện tại chưa có người dùng nào.</td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </section>
                </div>
                <div style="padding-top: 15px;">
                    <?php echo $this->paging; ?>
                </div>
            </section>
        </div>
    </div>
</section>