<?php  
echo "<pre>";
print_r($infoForm);
echo "</pre>";
?>
<div class="container">
	<h1>[<?php echo $infoForm->name ?>]</h1>
	<br/>
	<div class="row box" id="addNameForm">
		<div class="col-md-12">
			<div class="row">

				<div class="col-md-6">
					<div class="form-group">					
						<label for="type">Name Class Form</label>
						<input type="text" width="360" value="" class="form-control" name="inputNameClassForm" />
						<!-- class="hide alert alert-danger alert-dismissable" -->
						<p class="hide text-danger" id="errorClassForm">
                        	Nhập tên Class Form để tiếp tục !
                        </p>
					</div>
				</div>		
				<div class="col-md-6">
					<div class="form-group">					
						<label for="type">Name Class Filter</label>
						<input type="text" value="" class="form-control" name="inputNameClassFilter"/>
						<!-- class="hide alert alert-danger alert-dismissable" -->
						<p class="hide text-danger" id="errorClassFilter">
                        	Nhập tên Class Filter để tiếp tục !
                        </p>
					</div>
				</div>			
				
			</div>
		</div>
		<div class="col-md-4 col-md-offset-5">
		 	<div class="form-group">
		 		<label>&nbsp;</label><br/>
		    	<button class="btn btn-primary" type="button" id="createForm">Create Form</button>
		    </div>
		</div>
	</div>

	<div class="row box viewCode hide">
		<!-- CODE FOR CLASS FORM -->
		<div class="col-md-6 ">
			<h3>Code For Class Form</h3>
			<button class="btn pull-right" type="button" data-clipboard-target="#classForm">
				<img src="https://zenorocha.github.io/clipboard.js/assets/images/clippy.svg" width="13" height="15">
			</button>
			<div  name="code" class="form-control code" >
				<code id="classForm">
					<span class="php-keyword">namespace</span> <span class="php-plain name-space">;</span><br/>
					<br/>
					<span class="php-keyword">use</span> <span class="php-plain">Zend\Form\Form;</span><br/>
					<br/>
					<span class="php-keyword">class</span> <span class="php-plain class-form-name"></span> <span class="php-keyword">extends</span> <span class="php-plain">Form{</span><br/>
						<!-- method construct -->
						<br/>
						<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">public function</span>  <span class="php-plain">__construct(){</span><br/>
								<?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">parent::__construct();</span><br/><br/>
						<div style="margin-left: 75px;">
								<?php echo $this->codeInput ?>
						</div>
						<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">}</span><br/>

						<!-- method showError -->
						<br/><br/>
						<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">public function</span>  <span class="php-plain">showError(){</span><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-keyword">if</span><span class="php-plain">(empty(</span><span class="php-variable">$this</span><span class="php-plain">->getMessages()))</span> <span class="php-keyword">return</span> false;<br/><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-variable">$error</span> <span class="php-plain">=</span> '&lt;div class="alert alert-danger alert-dismissible fade in" role="alert"&gt; &lt;button type="button" class="close" data-dismiss="alert" aria-label="Close"&gt;&lt;span aria-hidden="true"&gt;×&lt;/span&gt;&lt;/button&gt;';<br/>
						 	<?php echo str_repeat("&nbsp;",10) ?><span class="php-keyword">foreach</span><span class="php-plain">(</span><span class="php-variable">$this</span><span class="php-plain">->getMessages()</span> <span class="php-keyword">as</span> <span class="php-variable">$key</span><span class="php-plain">=></span><span class="php-variable">$val</span><span class="php-plain">){</span><br/>
								<?php echo str_repeat("&nbsp;",15) ?><span class="php-variable">$error</span> <span class="php-plain">.=</span> <span class="php-keyword">sprintf</span><span class="php-plain">(</span>'&lt;p&gt;&lt;b&gt;%s : &lt;/b&gt;%s&lt;/p&gt;'<span class="php-plain">,</span><span class="php-keyword">ucfirst</span><span class="php-plain">(</span><span class="php-variable">$this</span><span class="php-plain">->convertToPrettyName(</span><span class="php-variable">$key</span><span class="php-plain">)),</span><span class="php-keyword">current</span><span class="php-plain">(</span><span class="php-variable">$val</span><span class="php-plain">));</span><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">}</span><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-variable">$error</span> <span class="php-plain">.=</span> '&lt;/div&gt;'<span class="php-plain">;</span><br/><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-keyword">return</span> <span class="php-variable">$error</span><span class="php-plain">;</span><br/>
						<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">}</span><br/>

						<!-- method convertToPrettyName -->
						<br/><br/>
						<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">private function</span> <span class="php-plain">convertToPrettyName(</span><span class="php-variable">$fieldName</span><span class="php-plain">){</span><br/>
					        <?php echo str_repeat("&nbsp;",10) ?><span class="php-keyword">switch</span><span class="php-plain">(</span><span class="php-variable">$fieldName</span><span class="php-plain">){</span><br/>
					            <?php if($infoForm->content != ""): ?>
						            <?php foreach($infoForm->content as $nameElement => $infoElement): ?>
						            	<?php if(array_key_exists('nameLabel',$infoElement['option']) && $infoElement['option']['nameLabel'] != '' && $infoElement['type'] != 'submit' && $infoElement['type'] != 'button'): ?>
								            <?php echo str_repeat("&nbsp;",15) ?><span class="php-keyword">case </span> <?php echo '"' . $nameElement . '"' ?> <span class="php-plain">:</span><br>
								            <?php echo str_repeat("&nbsp;",20) ?><span class="php-keyword">return</span> <?php echo '"' . $infoElement['option']['nameLabel'] . '"' ?><span class="php-plain">;</span><br/>
								            <?php echo str_repeat("&nbsp;",20) ?><span class="php-keyword">break</span><span class="php-plain">;</span><br/>
						        		<?php endif; ?>
						        	<?php endforeach; ?>
						        <?php endif; ?>
					        <?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">}</span><br/>
					    <?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">}</span><br/>
					<span class="php-plain">}</span><br/>
				</code>
			</div>
		</div>
		<!-- END CODE FOR CLASS FORM -->
		
		<!-- CODE FOR VALIDATE AND FILTER -->
		<div class="col-md-6 ">
			<h3>Code For Class Filter And Validate</h3>
			<button class="btn pull-right" type="button" data-clipboard-target="#validateFilter">
				<img src="https://zenorocha.github.io/clipboard.js/assets/images/clippy.svg" width="13" height="15">
			</button>
			<div  name="code" class="form-control code">
				<code id="validateFilter">
					<span class="php-keyword">namespace</span> <span class="php-plain name-space">;</span><br/>
					<br/>
					<span class="php-keyword">use</span> <span class="php-plain">Zend\InputFilter\InputFilter;</span><br/>
					<br/>
					<span class="php-keyword">class</span> <span class="php-plain class-validate-filter-name"></span> <span class="php-keyword">extends</span> <span class="php-plain">InputFilter{</span><br/>
					<br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">public function</span>  <span class="php-plain">__construct() {</span><br/>
					<div style="margin-left: 75px;">
							<?php echo $this->codeValidateAndFilter ?>
					</div>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">}</span><br/>
					<span class="php-plain">}</span>
				</code>
			</div>
		</div>
		<!-- END CODE FOR VALIDATE AND FILTER -->

		<!-- CODE FOR MODULE.PHP -->
		<div class="col-md-6">
			<h3>Code For Module(Module.php)</h3>
			<button class="btn pull-right" type="button" data-clipboard-target="#module">
				<img src="https://zenorocha.github.io/clipboard.js/assets/images/clippy.svg" width="13" height="15">
			</button>
			<div  name="code" class="form-control code">
				<code id="module">
					<span class="php-keyword">use</span> <span class="php-plain use-name-space">;</span><br/>
					<span class="php-keyword">use</span> <span class="php-plain use-name-space">;</span><br/>
					<br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">public function</span> <span class="php-plain">getFormElementConfig(){</span><br/>
				        <?php echo str_repeat("&nbsp;",10) ?><span class="php-keyword">return</span> <span class="php-plain">array(</span><br/>
				            <?php echo str_repeat("&nbsp;",15) ?>"factories" <span class="php-plain">=> array(</span><br/>       
				                <?php echo str_repeat("&nbsp;",20) ?><?php echo '"' . $infoForm->name .'"' ?> <span class="php-plain">=></span> <span class="php-keyword">function(</span><span class="php-variable">$sm</span><span class="php-plain">){</span><br/>            
				                    <?php echo str_repeat("&nbsp;",25) ?><span class="php-variable">$form</span>   <span class="php-plain">=</span> <span class="php-keyword">new</span> <span class="php-plain class-form-name-module">;</span><br/>
				                    <?php echo str_repeat("&nbsp;",25) ?><span class="php-variable">$form</span><span class="php-plain">->setInputFilter(</span><span class="php-keyword">new</span> <span class="php-plain "><span class="class-validate-filter-name-module"></span>);</span><br/>
					                <?php echo str_repeat("&nbsp;",25) ?><span class="php-keyword">return</span> <span class="php-variable">$form</span><span class="php-plain">;</span><br/>
				                <?php echo str_repeat("&nbsp;",20) ?><span class="php-plain">},</span><br/>
				            <?php echo str_repeat("&nbsp;",15) ?><span class="php-plain">)</span><br/>
				        <?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">);</span><br/>
				    <?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">}</span><br/>
				</code>
			</div>
		</div>
		<!-- END CODE FOR MODULE.PHP -->

		<!-- CODE FOR ACTION(CONTROLLER) -->
		<div class="col-md-6">
			<h3>Code For Action(Controller)</h3>
			<button class="btn pull-right" type="button" data-clipboard-target="#actionController">
				<img src="https://zenorocha.github.io/clipboard.js/assets/images/clippy.svg" width="13" height="15">
			</button>
			<div  name="code" class="form-control code">
				<code id="actionController">
					<br/>
					<span class="php-keyword">use</span> <span class="php-plain">Zend\View\Model\ViewModel;</span><br/>
					<br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-variable">$form</span> <span class="php-plain">=</span> <span class="php-variable">$this</span><span class="php-plain">->getServiceLocator()->get(</span>'FormElementManager'<span class="php-plain">)->get(</span><?php echo '"' . $infoForm->name .  '"' ?><span class="php-plain">);</span><br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">if</span><span class="php-plain">(</span><span class="php-variable">$this</span><span class="php-plain">->request->isPost()){</span><br/>
					<?php echo str_repeat("&nbsp;",10) ?><span class="php-variable">$form</span><span class="php-plain">->setData(</span><span class="php-variable">$this</span><span class="php-plain">->request->getPost());</span><br/>
					<?php echo str_repeat("&nbsp;",10) ?><span class="php-keyword">if</span><span class="php-plain">(</span><span class="php-variable">$form</span><span class="php-plain">->isValid()){</span><br/>
						<?php echo str_repeat("&nbsp;",15) ?><span class="php-variable">$data</span>  <span class="php-plain">=</span>   <span class="php-variable">$form</span><span class="php-plain">->getData();</span><br/>
					<?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">}</span><br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">}</span><br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">return new</span> <span class="php-plain">ViewModel([</span><br/>
						<?php echo str_repeat("&nbsp;",10) ?>"form" <span class="php-plain">=></span> <span class="php-variable">$form</span><br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">]);</span><br/>
				</code>
			</div>
		</div>
		<!-- END CODE FOR ACTION(CONTROLLER) -->
		
		<!-- CODE FOR VIEW -->
		<div class="col-md-6">
			<h3>Code For View</h3>
			<button class="btn pull-right" type="button" data-clipboard-target="#view">
				<img src="https://zenorocha.github.io/clipboard.js/assets/images/clippy.svg" width="13" height="15">
			</button>
			<div  name="code" class="form-control code">
				<code id="view">
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-variable">$form</span><span class="php-plain">->prepare();</span><br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">echo</span> <span class="php-variable">$form</span><span class="php-plain">->showError();</span><br/>
					<br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">echo</span> <span class="php-variable">$this</span><span class="php-plain">->form()->openTag(</span><span class="php-variable">$form</span><span class="php-plain">);</span><br/>
					    <?php if( $infoForm->content != ""): ?>
						    <?php foreach($infoForm->content as $nameElement => $infoElement): ?>
						    	<?php if($infoElement['type'] !== 'submit' && $infoElement['type'] !== 'button' && $infoElement['type'] !== 'reset'): ?>
						    		<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">echo</span> <span class="php-variable">$this</span><span class="php-plain">->formLabel(</span><span class="php-variable">$form</span><span class="php-plain">->get(</span><?php echo "'" . $nameElement . "'" ?><span class="php-plain">))</span> <span class="php-keyword">.</span><span class="php-variable">$this</span><span class="php-plain">->formElement(</span><span class="php-variable">$form</span><span class="php-plain">->get(</span><?php echo "'" . $nameElement . "'" ?><span class="php-plain">));</span><br/>
						    	<?php else: ?>
						    		<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">echo</span> </span><span class="php-variable">$this</span><span class="php-plain">->formElement(</span><span class="php-variable">$form</span><span class="php-plain">->get(</span><?php echo "'" . $nameElement . "'" ?><span class="php-plain">));</span><br/>
								<?php endif; ?>
							<?php endforeach; ?>
						<?php endif; ?>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">echo</span> <span class="php-variable">$this</span><span class="php-plain">->form()->closeTag();</span><br/>
				</code>
			</div>
		</div>
		<!-- END CODE FOR ACTION(CONTROLLER) -->
	</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js"></script>
<script>
	$("document").ready(function(){
		new Clipboard('.btn');
		$("#createForm").on("click",function(){
			flag  = true;
			if($("[name=inputNameClassForm]").val() === ""){
				$("#errorClassForm").removeClass("hide");
				flag = false;
			}else{
				$("#errorClassForm").addClass("hide");
				var arr = $("[name=inputNameClassForm]").val().split("\\");
				var classForm = arr.pop();
				$(".name-space").eq(0).text(arr.join("\\") + ";");
				$(".class-form-name").text(classForm);
				$(".class-form-name-module").text(classForm + "();");
				$(".use-name-space").eq(0).text($("[name=inputNameClassForm]").val() + ";");
				flag = true;
			}

			if($("[name=inputNameClassFilter]").val() === ""){
				$("#errorClassFilter").removeClass("hide");
				flag = false;
			}else{
				$("#errorClassFilter").addClass("hide");
				var arr = $("[name=inputNameClassFilter]").val().split("\\");
				var classFilter = arr.pop();
				$(".class-validate-filter-name").text(classFilter);
				$(".class-validate-filter-name-module").text(classFilter + "()");
				$(".name-space").eq(1).text(arr.join("\\") + ";");
				$(".use-name-space").eq(1).text($("[name=inputNameClassFilter]").val() + ";");
				flag = true;
			}

			if(flag){
				$(".viewCode").removeClass("hide");
			}else{
				$(".viewCode").addClass("hide");
			}
		})
	})
</script>
