
<div class="container">
	<div class="row box" id="addNew">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">					
					    <label for="type">Type</label>
					    <select class="form-control" name="typeElement" id="typeElement">
					    	<option value="button">Button</option>
					    	<option value="checkbox">Checkbox</option>
					    	<option value="color">Color</option>
					    	<option value="date">Date</option>
					    	<option value="datetime">Datetime</option>
					    	<option value="dateime-local">Datetime-local</option>
					    	<option value="email">Email</option>
					    	<option value="file">File</option>
					    	<option value="hidden">Hidden</option>
					    	<option value="image">Image</option>
					    	<option value="month">Month</option>
					    	<option value="number">Number</option>
					    	<option value="password">Pasword</option>
					    	<option value="radio">Radio</option>
					    	<option value="range">Range</option>
					    	<option value="reset">Reset</option>
					    	<option value="search">Search</option>
					    	<option value="Submit">Submit</option>
					    	<option value="Tel">Tel</option>
					    	<option value="text">Text</option>
					    	<option value="time">Time</option>
					    	<option value="url">Url</option>
					    	<option value="week">Week</option>
					    </select>
				    </div>
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group">
				    	<label for="name">Name</label>
				    	<input type="text" id="nameElement" name="nameElement" class="form-control"/>
				    </div>
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group">
				 		<label>&nbsp;</label><br/>
				    	<button class="btn btn-primary" id="addNewElement">Add new element</button>
				    </div>
				 </div>
			    	
			</div>
			
		</div>
	</div>
	
	<div class="row box hide" id="elementAttrs">
		
		<div class="col-md-6">
			<h3> [...] Element</h3>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">					
					    <label for="id">ID</label>
					    <input type="text" id="idElement" name="idElement" class="form-control"/>
				    </div>
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group">
				    	<label for="class">Class</label>
				    	<input type="text" id="classElement" name="classElement" class="form-control"/>
				    </div>
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group">
				 		<label for="placeElement">Placeholder</label><br/>
				    	<input type="text" name="placeElement" id="placeElement" class="form-control"/>
				    </div>
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group">
				 		<label for="valueElement">Value</label><br/>
				    	<input type="text" name="valueElement" id="valueElement" class="form-control"/>
				    </div>
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group">
				 		<label for="attrElement">Attributes</label><br/>
				    	<textarea class="form-control" name="attrElement" placeholder="onclick : function()" id="attrElement" cols="30" rows="5"></textarea>
				    </div>
				 </div>
				 
			</div>
			<hr />
			<div class="row">	
				 <div class="col-md-8">
				 	<div class="form-group">
				 		<label for="validateElement">Validate</label><br/>
				    	<select name="validateElement" id="validateElement" class="form-control">
				    		<?php
				    		
				    		 	$list = "";
				    		 	foreach($this->validateElement as $vali){
				    		 		$list .= '<option value="'. strtolower($vali['name']) .'">'. $vali['name'] .'</option>';
				    		 	}
				    		 	echo $list;
				    		 ?>
				    	
				    	</select>
				    </div>
				    

				    <ul id="validateList">
				    	
				    </ul>
				    
				    <!-- template validate option -->
				    <div class="col-md-12 validate-template hide">
				    	<form id="myForm">
	    					<div id="showtemplate"></div>              
						                                                 
	                        <div class="form-group col-md-12">	   
		                    	<button class="btn btn-primary" id="accept">Accept</button>
		                    	<button class="btn btn-info" id="cancel">Cancel</button>		        			    
	                        </div>
                        </form>
					    
				    </div>  
				    <!-- END template validate option -->  
				    
				 </div>
				 
				 <div class="col-md-4">
				 	<div class="form-group ">
				 		<label>&nbsp;</label><br/>
				    	<button class="btn btn-primary" id="setValidate">Set validate</button>
				    </div>
				 </div> 
				 
			</div>
			
		</div>
		
		<div class="pull-right col-md-6 display-code">
			<h3>Code</h3>
			<textarea  name="code" id="code" cols="65" rows="20" class="form-control"></textarea>
		</div>
		
		<div class="col-md-6 col-md-offset-3 text-center">
			<button class="btn btn-primary" id="create">Create</button>
		</div>
		
	</div>
	
</div>
<?php $url = $this->url('code/default',array('action' => 'loadTemplate')) ?>
<script type="text/javascript">
	$(document).ready(function(){
		var nameElement,typeElement;
		$("#addNewElement").on("click",function(){
			nameElement = $("#nameElement").val();
			typeElement = $("#typeElement").val();
			
			//show form Add Atrributes Element
			$("#elementAttrs").removeClass("hide");
			changeIdInput(nameElement);			
		})
		
		$("#setValidate").on("click",function(){
		    var validateValue = $("#validateElement :selected").val();
		    var validateName  = $("#validateElement :selected").text();
		   
		    
		    $("#validateList").append(addOptionValidate(validateValue,validateName) );

		    $(".show-option-validate").on('click',function(){
			    var self = this;
		    	var fileName = $(this).attr("href");
				fileName = fileName.replace('#','') + '.php';	
			
				$.ajax({
					url  	 : "<?php echo BASE_URL .  $url ?>",
					data 	 : { fileName : fileName },
					type 	 : 'GET',
					dataType : 'json',
					success : function(data){
						$("#showtemplate").empty();

						var templateFormated = data.template.replace(/my_element/g,nameElement);
						$("#showtemplate").html(templateFormated);
						showValidateTemplate('.show-option-validate');


						$(".removeVal").on('click',function(){
							$(this).parents('li').remove();
						})

						$("#cancel").on('click',function(){
							hideValidateTemplate();

							return false;
						})

						$("#accept").on('click',function(){
							// console.log($("input[name='city[validate][between][min]']").val());
							// $("#myForm :input").each(function(){
								
							// 	if($(this).is(":checkbox")){
							// 		if($(this).is(":checked")){
							// 			// console.log($(this).val())
							// 			console.log($(this).attr('name'))
							// 		}
							// 	}else{
							// 		// console.log($(this).val());
							// 		console.log($(this).attr('name'))
							// 	}
								
							// })
							var str = ($("#myForm").serialize());
							$(self).next('i').html(str);
							hideValidateTemplate();
							return false;
						})
					}
				})
			})

			
		})
		
		
		
		
	
	})

	function addOptionValidate(validateValue,validateName){
		return '<li><a class="show-option-validate" href="#' + validateValue + '">' + validateName + '</a> <span class="removeVal glyphicon glyphicon-remove"></span> <i>Lorem ipsum dolor sit amet.</i></li>';
	}
	
	function changeIdInput(nameElement){
		$("#elementAttrs h3:first").text("[" + nameElement + "] Element")
		$("#idElement").attr('name',nameElement + "[id]");
		$("#classElement").attr('name',nameElement + "[class]");
		$("#placeElement").attr('name',nameElement + "[placeholder]");
		$("#valueElement").attr('name',nameElement + "[value]");
		$("#attrElement").attr('name',nameElement  + "[attr]");
	}
	
	function showValidateTemplate(selector , template){
		$(selector).parents("ul#validateList").hide();
		$(".validate-template").addClass("animated fadeIn").removeClass('hide')
	}
	
	function hideValidateTemplate(selector , template){
		$("#validateList").show();
		$(".validate-template").removeClass("animated fadeIn").addClass('hide')
	}
	
</script>