<?php $urlActionValidateForm = BASE_URL. $this->url('code/default',['action' => 'validate']) ?>
<div class="container">
	<!-- ADD NEW FORM -->
	<form id="addNameForm" action="post">
		<div class="row box" id="addNameForm">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">					
							<label for="type">Name Form</label>
							<input type="text" width="360" class="form-control" name="inputNameForm" />
							<!-- class="hide alert alert-danger alert-dismissable" -->
							<p class="hide text-danger" id="errorNameForm">
                            	Nhập tên Form để tiếp tục !
                            </p>
						</div>
					</div>		
					<div class="col-md-4">
						<div class="form-group">					
							<label for="type">Form action</label>
							<input type="text" class="form-control" name="formAction"/>
						</div>
					</div>			
					<div class="col-md-4">
						<div class="form-group">					
							<label for="type">Class Form</label>
							<input type="text" class="form-control" name="formClass"/>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">					
							<label for="type">ID Form</label>
							<input type="text" class="form-control" name="formId"/>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">					
							<label for="type">Method Form</label>
							<select class="form-control" name="formMethod">
								<option value="post">POST</option>
								<option value="get">Get</option>
							</select>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">					
							<label for="type">Entype Form</label>
							<select class="form-control" name="formEntype">
								<option value="empty">Default</option>
								<option value="multipart/form-data">Multipart/form-data</option>
								<option value="application/x-www-form-urlencoded">Application/x-www-form-urlencoded</option>
								<option value="text/plain">Text/plain</option>
							</select>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">					
							<label for="type">Other</label>
							<input type="text" placeholder="a1:v1,a2:v2" class="form-control" name="formOther"/>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-md-offset-5">
			 	<div class="form-group">
			 		<label>&nbsp;</label><br/>
			    	<button class="btn btn-primary" type="button" id="createForm">Create Form</button>
			    </div>
			</div>
		</div>	
	</form>
	<!-- END ADD NEW FORM  -->

	<!-- ADD NEW ELEMENT -->
	<form id="validateForm" class="hide" method="post" action ="<?php echo $urlActionValidateForm ?>">
		<div class="row box" id="addNew">
			<div class="col-md-12">
				<div class="row">					 
				 	<div class="col-md-4">
					 	<div class="form-group">
					    	<label for="name">Name Element</label>
					    	<input type="text" id="nameElement" name="nameElement" class="form-control"/>
					    </div>
					</div>
					 
					<div class="col-md-4">
					 	<div class="form-group">
					 		<label>&nbsp;</label><br/>
					    	<button class="btn btn-primary" type="button" id="addNewElement">Add new element</button>
					    	<button type="button" class="btn btn-success" onclick="submitForm()" id="createElement">Save</button>
					    	<button type="button" class="btn btn-success" onclick="submitForm()" id="smartButtonSave">Save</button>
					    </div>
					</div>
				    	
				</div>
				
			</div>
		</div>
		<!-- END ADD NEW ELEMENT -->
		<div class="row box hide elementAttrs" >
			<div class="wrapper-1">
				<div class="col-md-12">
					<span class="hide span-name-element-hidden pull-left"></span>
					<span class="glyphicon glyphicon-remove pull-right removeElement" onclick="removeElement(this)"></span>
					<span class="glyphicon glyphicon-minus pull-right openElement"></span>
				</div>
				<div class="wrap">
					<div class="col-md-6">
						<h3 class="name-element">[...] Element</h3>
						<input type="hidden" name="name" class="input-name-element-hidden">
						<div class="row" style="margin-bottom: 30px;">
							<div class="col-md-6 tab tabAttribute">
								<h4>Attributes</h4>
							</div>
							<div class="col-md-6 tab tabOption">
								<h4>Options</h4>
							</div>
						</div>
						<!-- ATTRIBUTES -->

						<div class="row attribute">
							<div class="col-md-4">
								<div class="form-group">					
								    <label for="type">Type</label>
								    <select class="form-control typeElement" name="typeElement">
								    	<option value="button">Button</option>
								    	<option value="checkbox">Checkbox</option>
								    	<option value="color">Color</option>
								    	<option value="date">Date</option>
								    	<option value="datetime">Datetime</option>
								    	<option value="dateime-local">Datetime-local</option>
								    	<option value="email">Email</option>
								    	<option value="file">File</option>
								    	<option value="hidden">Hidden</option>
								    	<option value="image">Image</option>
								    	<option value="month">Month</option>
								    	<option value="number">Number</option>
								    	<option value="password">Pasword</option>
								    	<option value="radio">Radio</option>
								    	<option value="range">Range</option>
								    	<option value="reset">Reset</option>
								    	<option value="search">Search</option>
								    	<option value="select">Select</option>
								    	<option value="submit">Submit</option>
								    	<option value="tel">Tel</option>
								    	<option value="text">Text</option>
								    	<option value="time">Time</option>
								    	<option value="url">Url</option>
								    	<option value="week">Week</option>
								    </select>
							    </div>
							</div>
							<div class="col-md-4">
								<div class="form-group">					
								    <label for="id">ID</label>
								    <input type="text"  name="idElement" class="form-control idElement"/>
							    </div>
							</div>
							 
							<div class="col-md-4">
							 	<div class="form-group">
							    	<label for="class">Class</label>
							    	<input type="text" name="classElement" class="form-control classElement"/>
							    </div>
							</div>
							 
							 <div class="col-md-4">
							 	<div class="form-group">
							 		<label for="placeElement">Placeholder</label><br/>
							    	<input type="text" name="placeElement"class="form-control placeElement"/>
							    </div>
							 </div>
							 
							 <div class="col-md-4">
							 	<div class="form-group">
							 		<label for="valueElement">Value</label><br/>
							    	<input type="text" name="valueElement"  class="form-control valueElement"/>
							    </div>
							 </div>

							 <div class="col-md-4">
							 	<div class="form-group">
							 		<label for="requiredElement">Required</label><br/>
							    	<input type="checkbox" class="form-control requiredElement" checked="checked" name="requiredElement"/>
							    </div>
							 </div>
							 
							 <div class="col-md-4">
							 	<div class="form-group">
							 		<label for="attrElement">Attributes</label><br/>
							    	<textarea class="form-control attrElement" name="attrElement" placeholder="attr1 : name1,attr2 : name2"  cols="30" rows="5"></textarea>
							    </div>
							 </div>
							 
						</div>
						<!-- END ATTRIBUTES -->

						<!-- OPTIONS -->
						<div class="row hide option">
							<div class="col-md-4">
								<div class="form-group">					
								    <label for="id">Label name</label>
								    <input type="text"  name="nameLabel" class="form-control nameLabel"/>
							    </div>
							</div>
							 
							<div class="col-md-4">
							 	<div class="form-group">
							    	<label for="class">Label class</label>
							    	<input type="text" name="classLabel" class="form-control classLabel"/>
							    </div>
							</div>
							 
							<div class="col-md-4">
							 	<div class="form-group">
							 		<label for="placeElement">For</label><br/>
							    	<input type="text" id="forLabel" class="form-control forLabel"/>
							    </div>
							</div>
							 
							
							
							<div class="selectbox hide">
								<div class="col-md-4">
								 	<div class="form-group">
								 		<label for="emptyOption">Empty option</label><br/>
								    	<input type="text" name="emptyOption" class="form-control emptyOption"/>
								    </div>
								</div>

								<div class="col-md-4">
								 	<div class="form-group">
								 		<label for="valueOption">Value option</label><br/>
								    	<input type="text" name="valueOption" placeholder="1,2,3,4" class="form-control valueOption"/>
								    </div>
								</div>

								<div class="col-md-4">
								    <div class="form-group">
								 		<label for="nameOption">Name option</label><br/>
								    	<input type="text" name="nameOption" placeholder="name1,name2,name3,name4" class="form-control nameOption"/>
								    </div>
								</div>
							</div>
						</div>
						<!-- END OPTIONS -->
						<hr />

						<div class="row">
							<div style="margin-bottom: 30px;">
								<div class="col-md-6 tab tabValidate">
									<h4>Validate</h4>
								</div>
								<div class="col-md-6 tab tabFilter">
									<h4>Filter</h4>
								</div>
							</div>
						</div>
						<!-- VALIDATE AREA -->
						<div class="row validateArea" >
							<div class="col-md-10">
							 	<div class="form-group" >
							 		<label>&nbsp;</label><br/>
							    	<select name="validateElement" class="form-control">
							    		<?php					    			
							    		 	$list = "<option value='not-validate'>Choose Validate Type</option>";
							    		 	foreach($this->validateElement as $vali){
							    		 		$list .= '<option value="'. ($vali['name']) .'">'. $vali['name'] .'</option>';
							    		 	}
							    		 	echo $list;
							    		?>
							    	</select>
							    </div>
							    <ul class="validateList"> </ul>    
							</div>				 
							<div class="col-md-2">
							 	<div class="form-group ">
							 		<label>&nbsp;</label><br/>
							    	<button class="btn btn-primary setValidate" type="button">Set validate</button>
							    </div>
							</div> 					 
						</div>
						<!-- END VALIDATE AREA -->

						<!-- FILTER AREA -->
						<div class="row hide filterArea" >
							<div class="col-md-10">
							 	<div class="form-group" >
							 		<label>&nbsp;</label><br/>
							    	<select name="filterElement" class="form-control">
							    		<?php				    			
							    		 	$list = "<option value='not-filter'>Choose Filter Type</option>";
							    		 	foreach($this->filterElement as $vali){
							    		 		$list .= '<option value="'. ($vali['name']) .'">'. $vali['name'] .'</option>';
							    		 	}
							    		 	echo $list;
							    		?>				    	
							    	</select>
							    </div>
							    <ul class="filterList"> </ul>    
							</div>					 
							<div class="col-md-2">
							 	<div class="form-group ">
							 		<label>&nbsp;</label><br/>
							    	<button class="btn btn-primary setFilter" type="button">Set filter</button>
							    </div>
							</div> 					 
						</div>
						<!-- END FILTER -->

					</div>

					<div class="pull-right col-md-6 display-code">
						<h3>Code</h3>
						<div class="row-show-code hide" style="margin-bottom: 70px;">
							<div class="col-md-6 tab elementForm">
								<h4>Element Form</h4>
							</div>
							<div class="col-md-6 tab filterValidate">
								<h4>Filter &amp; Validate</h4>
							</div>
						</div>

						<div  name="code" class="form-control code">
						
						</div>
					</div>
				
					<div class="col-md-6 col-md-offset-3 text-center" style="margin-top:80px;margin-bottom:20px">
						<button type="button" class="btn btn-primary previewElement" >Preview Code</button>
					</div>
				</div>
			</div>
		</div>
	</form>
	<input type="hidden" name="formIdHidden" />
</div>
<?php $url = $this->url('code/default',array('action' => 'loadTemplate')) ?>




<script type="text/javascript">
	$(document).ready(function(){
		var firstTime = false;
		var flagName  = '';

		createFormDraf();
		// smartSaveButton();

		$("#addNewElement").on("click",function(){
			if(flagName === ''){
				flagName = $("#nameElement").val();
			}

			if(firstTime === false){ //============= first click :  show form ==============
				firstTime         = true;			
				var nameElement   = flagName;			
				var firstSelector = '.wrapper-' + nameElement;

				// change class wrapper with name of element
				$(".wrapper-1").attr('class','wrapper-'+nameElement);
				// add nameElement ro span hidden
				$(firstSelector + " >  div:first > span:first").text("[" + nameElement + "] Element");

				//show form AddAtrributesElement
				$(".elementAttrs").removeClass("hide");

				allMainAction(firstSelector,nameElement);

			}else{ //========== not first click :  append form =======================
				var nameElementNotFirst = $("#nameElement").val();
				var notFirstSelector    = ".wrapper-" + nameElementNotFirst;
				// create AnotherForm
				var clone               = $(".elementAttrs:first").clone().find("input:text, textarea").val("").end()
																			.find(".validateList, .filterList, .code").html("").end()										
																			.find(".selectbox").removeClass('hide').addClass('hide').removeClass('animated bounce').end()
																			.appendTo('#validateForm');
				// change class wrapper with name of element
				$(".wrapper-" + flagName).not(":first").attr('class',"wrapper-" + nameElementNotFirst);
				// add nameElement ro span hidden
				$(notFirstSelector + " >  div:first > span:first").text("[" + nameElementNotFirst + "] Element");

				allMainAction(notFirstSelector,nameElementNotFirst);
			}
		})
	})





	function allMainAction(selector,nameElement){
		changeIdInput(selector,nameElement);
		openTab(selector);
		showOptionSelectBox(selector);
		showAndHideElement(selector);

		$(selector + " .setValidate").on("click",function(){
			HandleFormOption(selector,nameElement,'.showTemplateValidate','validate');
		});//handle for Validate

		$(selector + " .setFilter").on("click",function(){
			HandleFormOption(selector,nameElement,'.showTemplateValidate','filter');
		});//handle for Filter

		$(selector + " .previewElement").on("click",function(){
			previewValidateForm(selector)
		});//handle for Preview Code
	}

	function showAndHideElement(selector){
		$(selector + " .openElement").on('click',function(e){
			//show name Element when close form
			var nameElementHidden = $(this).prev().prev();
			
			if(nameElementHidden.hasClass('hide')){
				nameElementHidden.removeClass('hide');
			}else{//hide name Element when open form
				nameElementHidden.addClass('hide');
			}
			openCloseElement(this);
		});
	}

	function removeElement(selector){
		if(window.confirm("Are you sure for remove this element ? ")) $(selector).parents(".elementAttrs:first").remove();	
	}

	function createFormDraf(selector){
		$("#createForm").click(function(){
			if($("input[name=inputNameForm]").val() === ""){
				$("#errorNameForm").removeClass("hide");
			}else{
				$("#errorNameForm").addClass("hide");
				$.ajax({
					url : "<?php echo $this->url('form/default',array('action' => 'addFormDraf')) ?>",
					type : 'POST',
					data : {
						'nameForm'   : $("input[name=inputNameForm]").val(),
						'actionForm' : $("input[name=formAction]").val(),
						'classForm'  : $("input[name=formClass]").val(),
						'idForm'     : $("input[name=formId]").val(),
						'methodForm' : $("select[name=formMethod]").val(),
						'entypeForm' : $("select[name=formEntype]").val(),
						'otherForm'  : $("input[name=formOther]").val(),
						'user_id'    : "<?php echo $userInfo->id ?>"
					},
					success : function(id){
						if(id !== ''){
							if($("#validateForm").hasClass("hide")){
								$("#validateForm").removeClass("hide");
							}
		
							$("input[name=formIdHidden]").val(id);
						}
					}
				})
			}
		})
	}

	function HandleFormOption(selectorMain,nameElement,selectorTemplate,type){
			if(type === 'validate'){
				var validateValue = $(selectorMain + " [name=validateElement] option:selected").val();
				var validateName  = $(selectorMain + " [name=validateElement] option:selected").text();
			}else{
				var validateValue = $(selectorMain + " [name=filterElement] option:selected").val();
				var validateName  = $(selectorMain + " [name=filterElement] option:selected").text();
			}
			
			var fileName      = validateValue.toLowerCase() + '.php';
	
		   	$.ajax({
				url  	 : "<?php echo BASE_URL .  $url ?>",
				data 	 : { 
					fileName : fileName ,
					type 	 : type
				},
				type 	 : 'GET',
				dataType : 'json',
				success  : function(data){
					
					if(data.template === 'no'){
						var haveTemplate = 'no';
		    			addValidateRow(selectorMain,validateValue,validateName,nameElement,haveTemplate,type);
					}else{
						var haveTemplate = 'yes';
		    			addValidateRow(selectorMain,validateValue,validateName,nameElement,haveTemplate,type);

						var templateFormated = data.template.replace(/my_element/g,nameElement);
						$(selectorMain + " li[name=" + validateValue + "] "+selectorTemplate).append(templateFormated);

						$(selectorMain + " .show-option-validate").on('click',function(){
							var self               = this;
							var classTemplate      = $(self).attr('href').toLowerCase();
							var selectorOfTemplate = selectorMain + ' .showTemplateValidate ' + classTemplate;
							
						    $(self).prev('span').removeClass('glyphicon-plus').addClass('glyphicon-minus');

						   	// console.log(classTemplate)

						    showValidateTemplate(selectorOfTemplate);
							
							$(selectorMain + " .cancel").on('click',function(){
								hideValidateTemplate(this,self);

								return false;
							})

							$(selectorMain + " .accept").on('click',function(){
								var str = $(selectorOfTemplate).serialize();
								
								createRowValidateHidden(str,'yes',self);
								hideValidateTemplate(this,self);

								self = null;

								return false;
							})
						})
					}
		    		$(selectorMain + " .removeVal").on('click',function(){
					    removeOption(this);
					})
							
				},
			})	
	}

	function showOptionSelectBox(selector = null){
		$(selector + " .typeElement").change(function(){
			if($(this).val() === 'select'){
				$(selector).find(".selectbox").removeClass('hide').addClass('animated bounce');
			}else{
				$(selector).find(".selectbox").addClass('hide').removeClass('animated bounce');
			}
		})
	}

	function openTab(selector = null){
		
		$(selector + " .tabAttribute").click(function(){
			$(selector).find(".attribute").removeClass('hide');
			$(selector).find(".option").addClass('hide');
		})
		$(selector + " .tabOption").click(function(){
			$(selector).find(".option").removeClass('hide');
			$(selector).find(".attribute").addClass('hide');
		})

		$(selector + " .tabValidate").click(function(){
			$(selector).find(".validateArea").removeClass('hide');
			$(selector).find(".filterArea").addClass('hide');
		})
		$(selector + " .tabFilter").click(function(){
			$(selector).find(".filterArea").removeClass('hide');
			$(selector).find(".validateArea").addClass('hide');
		})
	}

	function submitForm(){
		$.ajax({
			url  : "<?php echo $this->url("form/default" , array('action' => 'addForm')) ?>",
			type : 'POST',
			data : {
				element : $("#validateForm").serialize(),
				formId : $("input[name =formId]").val()
			},	
			success : function(data){
				window.location.href = "<?php echo $this->url('form') ?>";
			}
		})
	}

	function previewValidateForm(selector = null){
		// console.log(selector); return false;
		var action = $("#validateForm").attr('action');
		$.ajax({
			url  : action,
			type : 'POST',
			data : {
				element  : $("#validateForm").serialize(),
				selector : selector 
			},
			success : function(data){
				var source = data.split('<div class="hide">superman</div>');
				// console.log(source);
				$(selector + ' .row-show-code').removeClass('hide').addClass('animated flipInX');
				
				$(selector + " .code").html(source[0]);
				
				$(selector + ' .filterValidate').click(function(){
					$(selector + ' .code').html(source[1]);
				});

				$(selector + ' .elementForm').click(function(){
					$(selector + ' .code').html(source[0]);
				});
			}
		})

	}

	function addValidateRow(selector,validateValue,validateName,nameElement,haveTemplate,type){
		if(type === 'validate'){
			// console.log(selector + " .validateList");
			$(selector + " .validateList").append(addOptionValidate(validateValue,validateName,nameElement,haveTemplate,type) );
		}else{
			$(selector + " .filterList").append(addOptionValidate(validateValue,validateName,nameElement,haveTemplate,type) );

		}
	}

	function removeOption(selector){	
		$(selector).parents('li').remove();
	}


	function createRowValidateHidden(str,haveTemplate = 'yes',selector = null){
		
		if(haveTemplate === 'yes'){
			var newArr = str.split('&');
			var html = ''
			$.each(newArr,function(index,val){
				val = val.replace(/%5B/g,'[');
				val = val.replace(/%5D/g,']');
				var option = val.split('=');
				html += '<input class="" type="hidden" name="' + option[0] + '" value="' + option[1] + '" />';
			})

			$(selector).parent('li').find('.hidden-edit').html(html);
		}	
	}

	function addOptionValidate(validateValue,validateName,nameElement,haveTemplate,type){
		var hiddenInputName    = 'filterName';
		var validateBreakChain = '';
		var nameValidateHidden = validateValue;
		//rename for filter-alpha and filter-alnum
		if(validateValue === 'Filter-Alpha') nameValidateHidden = 'Alpha';
		if(validateValue === 'Filter-Alnum') nameValidateHidden = 'Alnum';

		// add break chain input hidden with type Validate
		if(type === 'validate'){
			var hiddenInputName    = 'validateName';
			var validateBreakChain = '<label class="checkbox-inline">Break chain on failure<input type="checkbox" checked name="' + nameElement + '[validateBreakChain][' + nameValidateHidden + ']"/></label>';
		}
		
		if(haveTemplate === 'yes'){//if have template handle with tag a
			return 	'<li name="' + validateValue +'">'+
						'<span class="glyphicon glyphicon-plus"></span><a onclick="return false" class="show-option-validate" href=".' + validateValue + '">' + validateName + '</a>' + 
						'<span class="removeVal glyphicon glyphicon-remove"></span>' + 
						validateBreakChain + 
						'<div class="showTemplateValidate col-md-12 hide" > </div>' + 
						'<input type="hidden" value="' + nameValidateHidden + '" name="' + nameElement + '[' + hiddenInputName + '][' + nameValidateHidden + ']"/>' + 
					'</li>';
		}else{//if no template prevent event with tag a 
			return 	'<li name="' + validateValue +'">' + 
						'<span class="glyphicon glyphicon-plus"></span><a onclick="return false" class="show-option-validate a-normal" href=".' + validateValue + '">' + validateName + '</a>' + 
						'<span class="removeVal glyphicon glyphicon-remove"></span>' + 
						validateBreakChain + 
						'<input type="hidden" value="' + nameValidateHidden + '" name="' + nameElement + '[' + hiddenInputName + '][' + nameValidateHidden + ']"/>' +
					'</li>';
		}
	}
	
	function changeIdInput(selector = null,nameElement =null){
		// console.log($(selector).html());		
		$(selector + " .name-element").text("[" + nameElement + "] Element");
		$(selector + " .input-name-element-hidden").val(nameElement);
		//name
		$(selector + " .input-name-element-hidden").attr('name', nameElement + "[name]");
		//type
		$(selector + " .typeElement").attr('name', nameElement + "[type]");
		//required
		$(selector + " .requiredElement").attr('name',nameElement  + "[required]");
		//atribute
		$(selector + " .idElement").attr('name',nameElement + "[attribute][id]");
		$(selector + " .classElement").attr('name',nameElement + "[attribute][class]");
		$(selector + " .placeElement").attr('name',nameElement + "[attribute][placeholder]");
		$(selector + " .valueElement").attr('name',nameElement + "[attribute][value]");
		$(selector + " .attrElement").attr('name',nameElement  + "[attribute][attr]");
		//option
		$(selector + " .nameLabel").attr('name',nameElement  + "[option][nameLabel]");
		$(selector + " .classLabel").attr('name',nameElement  + "[option][classLabel]");
		$(selector + " .forLabel").attr('name',nameElement  + "[option][forLabel]");
		$(selector + " .emptyOption").attr('name',nameElement  + "[option][emptyOption]");
		$(selector + " .valueOption").attr('name',nameElement  + "[option][valueOption]");
		$(selector + " .nameOption").attr('name',nameElement  + "[option][nameOption]");
	}
	
	function showValidateTemplate(selector){
		$(selector).parents('.showTemplateValidate').removeClass('hide').addClass("animated zoomIn");
	}
	
	function hideValidateTemplate(selector,tagA){
		$(selector).parents('.showTemplateValidate').removeClass("animated zoomIn").addClass('hide');
		$(tagA).prev('span').removeClass('glyphicon-minus').addClass('glyphicon-plus');
	}
	
	function openCloseElement(selector){
		$(selector).parent().next().slideToggle();
		if($(selector).hasClass('glyphicon-plus')){
			$(selector).removeClass("glyphicon-plus").addClass("glyphicon-minus");
		}else{
			$(selector).removeClass("glyphicon-minus").addClass("glyphicon-plus");
		}
	}
	
	// function smartSaveButton(){
	// 	var offset = 250;
	// 	var duration = 300;
		 
	// 	$(window).scroll(function() {
		 
	// 	if ($(this).scrollTop() > offset) {
	// 	 	$("#validateForm").addClass("fixed");
	// 		$("#smartButtonSave").fadeIn(duration);
		 
	// 	} else {
	// 	 	$("#validateForm").removeClass("fixed");		 
	// 		$("#smartButtonSave").fadeOut(duration);
		 
	// 	}
		 
	// 	});
		 
		 
		// $(".back-to-top").click(function(event) {
		 
		// event.preventDefault();
		 
		// $("html, body").animate({scrollTop: 0}, duration);
		 
		// return false;
 
// })
	// }

</script>